Card issue10
CMPUT301F20T41/boromi pull request #35
Opened 2020-10-29 21:11 UTC by BWAGG

made some mistakes so 2 more commits than i needed. Will be making more adjustments to the cards as i go, but just wanted to give an idea of what they look like for now.

2020-10-30 03:18 UTC, mingyaang commented
Don't worry about commit count, when this is squash merged into the repo it will all become 1 commit :)

2020-10-30 03:19 UTC, mingyaang commented
For this one I will let someone else review since I'm not as experienced in the UI, but the elements look good from what I saw @2pm :)

2020-10-31 20:00 UTC, blchelle requested changes
Very small changes required. I don't think you need the accept_circle or reject_circle.xml files, see my comment for a suitable replacement.

Other than that I think I just have one requested change in searched.xml so that the ISBN text is consistent with everything else.

2020-10-31 20:00 UTC, blchelle commented on app/src/main/res/drawable/accept_circle.xml
> +<?xml version="1.0" encoding="utf-8"?>
I don't think this component is necessary since the accept icon is already circular
Then in line 29 of req_list_entry.xml you can 
```xml
android:background="@color/colorIconLight"
```

2020-10-31 20:00 UTC, blchelle commented on app/src/main/res/drawable/reject_circle.xml
> +<?xml version="1.0" encoding="utf-8"?>
I don't think this component is necessary since the accept icon is already circular
Then in line 42 of req_list_entry.xml you can

android:background="@color/colorIconLight"

2020-10-31 20:00 UTC, blchelle commented on app/src/main/res/layout/reqbm.xml
> +<?xml version="1.0" encoding="utf-8"?>
What does reqbm stand for?

2020-10-31 20:00 UTC, blchelle commented on app/src/main/res/layout/reqom.xml
> +<?xml version="1.0" encoding="utf-8"?>
what does req om stand for

2020-10-31 20:00 UTC, blchelle commented on app/src/main/res/layout/searched.xml
> +                    android:textSize="8sp"></TextView>
Could you change this to 
```xml
            <TextView
                android:id="@+id/ISBN"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="ISBN: #1234567890123"
                android:textAppearance="@style/TextAppearance.AppCompat.Small"
                android:textSize="10sp"></TextView>
```

2020-10-31 20:01 UTC, BWAGG commented on app/src/main/res/layout/reqbm.xml
> +<?xml version="1.0" encoding="utf-8"?>
requested by me

2020-10-31 20:02 UTC, BWAGG commented on app/src/main/res/layout/reqom.xml
> +<?xml version="1.0" encoding="utf-8"?>
requested of me

2020-10-31 20:17 UTC, blchelle approved these changes
Yep looks good to me 👍, Go ahead and squash merge so you can filter out all your unwanted commit messages

2020-10-31 21:04 UTC, merged